sudo: required
language: java
jdk:
  - oraclejdk8
before_install:
  - curl http://www.jpm4j.org/install/script > jpmInstall.sh
  - sudo sh jpmInstall.sh
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
after_success:
  - sudo cat target/site/jacoco/jacoco.xml
  - sudo codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml --debug