sudo: required
language: java
jdk:
  - oraclejdk8
before_install:
  - curl -sL http://bit.ly/jpm4j >jpm4j.jar
  - sudo java -jar jpm4j.jar -g init
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
after_success:
  - codacy-coverage-reporter -l Java -r ./target/site/jacoco/jacoco.xml --prefix ./src/main/java/