sudo: required
language: java
jdk:
  - oraclejdk8
before_install:
  - sudo curl https://www.jpm4j.org/install/script | sh
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
after_success:
  - codacy-coverage-reporter -l Java -r ./target/site/jacoco/jacoco.xml --prefix ./src/main/java/